# Generated by Django 4.1.4 on 2023-01-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_doctor_verify_receptionist_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Clinics', 'General Clinics'), ('Mental Health', 'Mental Health'), ('Eye Specialists', 'Eye Specialists'), ('Cancer Specialists', 'Cancer Specialists'), ('Ayurveda Specialists', 'Ayurveda Specialists'), ('ENT specialists', 'ENT specialists'), ('Skin, Sex and Hair', 'Skin, Sex and Hair'), ('Child Health', 'Child Health'), ('Diabetes, Thyroid and Hormonal', 'Diabetes, Thyroid and Hormonal'), ('Pregnancy and Infertility', 'Pregnancy and Infertility'), ('Kidney Specialists', 'Kidney Specialists'), ('Dental Cares', 'Dental Cares'), ('Physiotherapy Centers', 'Physiotherapy Centers'), ('Diet and Nutrition', 'Diet and Nutrition')], default='General Clinics', max_length=120),
        ),
    ]
