# Generated by Django 4.1.4 on 2023-01-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(blank=True, upload_to='doctors_image'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='short_description',
            field=models.TextField(blank=True, default='Specialist Doctor'),
        ),
    ]
