# Generated by Django 4.1.4 on 2023-01-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_appointments_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='doctor_review',
            field=models.TextField(blank=True),
        ),
    ]
