# Generated by Django 4.1.4 on 2023-01-12 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_report_doctor_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcomment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
