# Generated by Django 4.1.4 on 2023-01-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_reviewcomment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='added_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
