# Generated by Django 4.1.4 on 2023-01-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_report_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
