# Generated by Django 4.1.4 on 2023-01-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_bills_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Khalti', 'Khalti')], default='Cash On Delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='bills',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
