# Generated by Django 4.1.4 on 2023-01-17 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_alter_healthpackages_description'),
        ('mainapp', '0021_rename_bill_unique_id_bills_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='extras.healthpackages'),
            preserve_default=False,
        ),
    ]
