# Generated by Django 4.1.4 on 2023-01-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_bills_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
