# Generated by Django 4.1.4 on 2023-01-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_bills_bill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
