# Generated by Django 4.1.4 on 2023-01-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPackageMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title_main', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, upload_to='package_image_main')),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
