# Generated by Django 4.1.4 on 2023-01-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_healthpackagemain'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackages',
            name='MainPackage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='extras.healthpackagemain'),
            preserve_default=False,
        ),
    ]
