# Generated by Django 4.1.4 on 2023-01-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_healthpackages_mainpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackages',
            name='package_price',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='healthpackages',
            name='total_tests',
            field=models.IntegerField(default=5),
        ),
    ]
