# Generated by Django 4.1.4 on 2023-01-17 08:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_healthpackages_package_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpackages',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
