# Generated by Django 4.1.4 on 2023-01-18 08:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0005_alter_healthpackages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcare',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
