# Generated by Django 4.1.4 on 2023-01-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0006_alter_childcare_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childcare',
            old_name='image',
            new_name='showcase_image',
        ),
        migrations.AddField(
            model_name='childcare',
            name='schedule_image',
            field=models.FileField(blank=True, null=True, upload_to='childcare_image_schedule'),
        ),
    ]
